# Generated by Django 4.2.7 on 2023-11-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
