# Generated by Django 4.2.7 on 2023-11-13 09:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='место')),
                ('time', models.DateTimeField(verbose_name='дата и время')),
                ('action', models.CharField(max_length=250, verbose_name='действие')),
                ('is_pleasurable', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('frequency', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='вознаграждение')),
                ('duration', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120)], verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
