# Generated by Django 4.2.7 on 2023-11-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('-id',), 'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
    ]
