# Generated by Django 4.2.7 on 2023-11-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='task_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='id выполняемой задачи'),
        ),
    ]
